# GENERATE EMBEDDED ASSETS ──────────────────────────────────────────────────
#
# Embeds every file directly under SOURCE_DIR into a generated C++ header as
# an array of entries exposed through an inline accessor function. Invoked
# at build time as:
#
#   cmake -DSOURCE_DIR=<dir> -DOUTPUT_FILE=<file> -DNAMESPACE=<namespace>
#         -DACCESSOR_NAME=<function-name> [-DENCODING=TEXT|HEX]
#         -P generate_embedded_assets.cmake
#
# ENCODING=TEXT (the default) reads each file as text and embeds it as a
# raw string literal, producing notex::assets::EmbeddedFile{name, content}
# entries. ENCODING=HEX instead reads each file as a hex-encoded byte
# stream, which is binary-safe, and produces
# notex::assets::EmbeddedHexFile{name, hex_content} entries; the caller is
# expected to decode these back into bytes at runtime.
#
# The custom command that runs this script depends on every file it globs,
# so editing, adding, or removing a file under SOURCE_DIR regenerates the
# header on the next build.

if(NOT DEFINED SOURCE_DIR
   OR NOT DEFINED OUTPUT_FILE
   OR NOT DEFINED NAMESPACE
   OR NOT DEFINED ACCESSOR_NAME)
  message(FATAL_ERROR "generate_embedded_assets.cmake requires SOURCE_DIR, "
                       "OUTPUT_FILE, NAMESPACE and ACCESSOR_NAME to be "
                       "defined.")
endif()

if(NOT DEFINED ENCODING)
  set(ENCODING TEXT)
endif()

if(ENCODING STREQUAL "HEX")
  set(STRUCT_TYPE "notex::assets::EmbeddedHexFile")
elseif(ENCODING STREQUAL "TEXT")
  set(STRUCT_TYPE "notex::assets::EmbeddedFile")
else()
  message(FATAL_ERROR "generate_embedded_assets.cmake: unknown ENCODING "
                       "'${ENCODING}' (expected TEXT or HEX).")
endif()

# Raw-string delimiter used to embed TEXT-encoded content verbatim. If a
# source file ever contains this exact closing sequence, the embedding
# would silently truncate, so generation fails loudly instead. Unused in
# HEX mode, where content is always plain hexadecimal text.
set(DELIMITER "NOTEX_ASSET")

file(GLOB ASSET_FILES LIST_DIRECTORIES false RELATIVE "${SOURCE_DIR}"
     "${SOURCE_DIR}/*")
list(SORT ASSET_FILES)
list(LENGTH ASSET_FILES ASSET_COUNT)

get_filename_component(OUTPUT_DIR "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")

file(
  WRITE "${OUTPUT_FILE}"
  "#pragma once

// Generated by cmake/generate_embedded_assets.cmake — do not edit by hand.
// Regenerated automatically whenever a source asset file changes.

#include \"notex/assets.hpp\"

#include <array>

namespace ${NAMESPACE} {

inline const std::array<${STRUCT_TYPE}, ${ASSET_COUNT}>&
${ACCESSOR_NAME}() {
    static const std::array<${STRUCT_TYPE}, ${ASSET_COUNT}>
        files{{
")

foreach(REL_PATH ${ASSET_FILES})
  if(ENCODING STREQUAL "HEX")
    file(READ "${SOURCE_DIR}/${REL_PATH}" FILE_CONTENT HEX)
    file(APPEND "${OUTPUT_FILE}"
         "        ${STRUCT_TYPE}{\"${REL_PATH}\", \"${FILE_CONTENT}\"},\n")
  else()
    file(READ "${SOURCE_DIR}/${REL_PATH}" FILE_CONTENT)

    string(FIND "${FILE_CONTENT}" ")${DELIMITER}\"" DELIMITER_POSITION)
    if(NOT DELIMITER_POSITION EQUAL -1)
      message(
        FATAL_ERROR
          "Asset '${REL_PATH}' contains the raw-string delimiter "
          "')${DELIMITER}\"' used by the embedding generator; change "
          "DELIMITER in generate_embedded_assets.cmake before proceeding.")
    endif()

    file(
      APPEND "${OUTPUT_FILE}"
      "        ${STRUCT_TYPE}{\"${REL_PATH}\", R\"${DELIMITER}(${FILE_CONTENT})${DELIMITER}\"},\n"
    )
  endif()
endforeach()

file(APPEND "${OUTPUT_FILE}" "    }};
    return files;
}

}  // namespace ${NAMESPACE}
")

message(STATUS "Embedded ${ASSET_COUNT} file(s) from ${SOURCE_DIR} into "
                "${OUTPUT_FILE}")
